{"uid":"568a08e052c1761f","name":"test_send_message","fullName":"tests.test_example.ExampleTestCase#test_send_message","historyId":"3bc4f3765c9b31fcf733254dd25c049d","time":{"start":1756971948821,"stop":1756971949219,"duration":398},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=139.0.7258.154)\nStacktrace:\n#0 0x55f3c41d908a <unknown>\n#1 0x55f3c3c78a70 <unknown>\n#2 0x55f3c3c6fcf1 <unknown>\n#3 0x55f3c3c61099 <unknown>\n#4 0x55f3c3c62de0 <unknown>\n#5 0x55f3c3c6143e <unknown>\n#6 0x55f3c3c60daa <unknown>\n#7 0x55f3c3c60a85 <unknown>\n#8 0x55f3c3c5e8ee <unknown>\n#9 0x55f3c3c5f0ca <unknown>\n#10 0x55f3c3c7bf99 <unknown>\n#11 0x55f3c3d16d65 <unknown>\n#12 0x55f3c3cf03e2 <unknown>\n#13 0x55f3c3d1614f <unknown>\n#14 0x55f3c3cf01b3 <unknown>\n#15 0x55f3c3cbc59b <unknown>\n#16 0x55f3c3cbd971 <unknown>\n#17 0x55f3c419e25b <unknown>\n#18 0x55f3c41a1fa9 <unknown>\n#19 0x55f3c4185339 <unknown>\n#20 0x55f3c41a2b58 <unknown>\n#21 0x55f3c4169c1f <unknown>\n#22 0x55f3c41c6118 <unknown>\n#23 0x55f3c41c62f6 <unknown>\n#24 0x55f3c41d8066 <unknown>\n#25 0x7fb75f89caa4 <unknown>\n#26 0x7fb75f929c3c <unknown>","statusTrace":"self = <test_example.ExampleTestCase testMethod=test_send_message>\n\n    def test_send_message(self):\n>       self.home.open(OLLAMA_URL)\n\ntests/test_example.py:31: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/home_page.py:21: in open\n    self.driver.get(url)\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:483: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:458: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fbd33cd4590>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#24 0x55f3c41d8066 \\\\u003Cunknown>\\\\n#25 0x7fb75f89caa4 \\\\u003Cunknown>\\\\n#26 0x7fb75f929c3c \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                try:\n                    value = json.loads(value_json)\n                    if isinstance(value, dict):\n                        if len(value) == 1:\n                            value = value[\"value\"]\n                        status = value.get(\"error\", None)\n                        if not status:\n                            status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                            message = value.get(\"value\") or value.get(\"message\")\n                            if not isinstance(message, str):\n                                value = message\n                                message = message.get(\"message\")\n                        else:\n                            message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=139.0.7258.154)\nE       Stacktrace:\nE       #0 0x55f3c41d908a <unknown>\nE       #1 0x55f3c3c78a70 <unknown>\nE       #2 0x55f3c3c6fcf1 <unknown>\nE       #3 0x55f3c3c61099 <unknown>\nE       #4 0x55f3c3c62de0 <unknown>\nE       #5 0x55f3c3c6143e <unknown>\nE       #6 0x55f3c3c60daa <unknown>\nE       #7 0x55f3c3c60a85 <unknown>\nE       #8 0x55f3c3c5e8ee <unknown>\nE       #9 0x55f3c3c5f0ca <unknown>\nE       #10 0x55f3c3c7bf99 <unknown>\nE       #11 0x55f3c3d16d65 <unknown>\nE       #12 0x55f3c3cf03e2 <unknown>\nE       #13 0x55f3c3d1614f <unknown>\nE       #14 0x55f3c3cf01b3 <unknown>\nE       #15 0x55f3c3cbc59b <unknown>\nE       #16 0x55f3c3cbd971 <unknown>\nE       #17 0x55f3c419e25b <unknown>\nE       #18 0x55f3c41a1fa9 <unknown>\nE       #19 0x55f3c4185339 <unknown>\nE       #20 0x55f3c41a2b58 <unknown>\nE       #21 0x55f3c4169c1f <unknown>\nE       #22 0x55f3c41c6118 <unknown>\nE       #23 0x55f3c41c62f6 <unknown>\nE       #24 0x55f3c41d8066 <unknown>\nE       #25 0x7fb75f89caa4 <unknown>\nE       #26 0x7fb75f929c3c <unknown>\n\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:232: WebDriverException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":5,"retriesStatusChange":false,"beforeStages":[{"name":"_unittest_setUpClass_fixture_ExampleTestCase","time":{"start":1756971940905,"stop":1756971940905,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"_unittest_setUpClass_fixture_ExampleTestCase::0","time":{"start":1756971949245,"stop":1756971949245,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_example"},{"name":"subSuite","value":"ExampleTestCase"},{"name":"host","value":"pkrvm7jw40e0xgp"},{"name":"thread","value":"2501-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_example"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"af7a404bb22e89e8","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//localhost%3A3000/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20localhost%3A3000.\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:910:5\ncheckReadyState@chrome://remote/content/marionette/navigate.sys.mjs:59:24\nonNavigation@chrome://remote/content/marionette/navigate.sys.mjs:348:39\nemit@resource://gre/modules/EventEmitter.sys.mjs:156:19\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.sys.mjs:33:25","time":{"start":1756971943630,"stop":1756971945582,"duration":1952}},{"uid":"c8331934a7aba9b9","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//localhost%3A3000/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20localhost%3A3000.\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:910:5\ncheckReadyState@chrome://remote/content/marionette/navigate.sys.mjs:59:24\nonNavigation@chrome://remote/content/marionette/navigate.sys.mjs:348:39\nemit@resource://gre/modules/EventEmitter.sys.mjs:156:19\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.sys.mjs:33:25","time":{"start":1756971943420,"stop":1756971945482,"duration":2062}},{"uid":"9e99813a03a28454","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//localhost%3A3000/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20localhost%3A3000.\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:910:5\ncheckReadyState@chrome://remote/content/marionette/navigate.sys.mjs:59:24\nonNavigation@chrome://remote/content/marionette/navigate.sys.mjs:348:39\nemit@resource://gre/modules/EventEmitter.sys.mjs:156:19\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.sys.mjs:33:25","time":{"start":1756971937212,"stop":1756971939639,"duration":2427}},{"uid":"fd945be6c03056f4","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=139.0.7258.154)\nStacktrace:\n#0 0x55d60ca9c08a <unknown>\n#1 0x55d60c53ba70 <unknown>\n#2 0x55d60c532cf1 <unknown>\n#3 0x55d60c524099 <unknown>\n#4 0x55d60c525de0 <unknown>\n#5 0x55d60c52443e <unknown>\n#6 0x55d60c523daa <unknown>\n#7 0x55d60c523a85 <unknown>\n#8 0x55d60c5218ee <unknown>\n#9 0x55d60c5220ca <unknown>\n#10 0x55d60c53ef99 <unknown>\n#11 0x55d60c5d9d65 <unknown>\n#12 0x55d60c5b33e2 <unknown>\n#13 0x55d60c5d914f <unknown>\n#14 0x55d60c5b31b3 <unknown>\n#15 0x55d60c57f59b <unknown>\n#16 0x55d60c580971 <unknown>\n#17 0x55d60ca6125b <unknown>\n#18 0x55d60ca64fa9 <unknown>\n#19 0x55d60ca48339 <unknown>\n#20 0x55d60ca65b58 <unknown>\n#21 0x55d60ca2cc1f <unknown>\n#22 0x55d60ca89118 <unknown>\n#23 0x55d60ca892f6 <unknown>\n#24 0x55d60ca9b066 <unknown>\n#25 0x7f575fc9caa4 <unknown>\n#26 0x7f575fd29c3c <unknown>","time":{"start":1756971936837,"stop":1756971937281,"duration":444}},{"uid":"9b49adb1d056f7d7","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=139.0.7258.154)\nStacktrace:\n#0 0x556743d2808a <unknown>\n#1 0x5567437c7a70 <unknown>\n#2 0x5567437becf1 <unknown>\n#3 0x5567437b0099 <unknown>\n#4 0x5567437b1de0 <unknown>\n#5 0x5567437b043e <unknown>\n#6 0x5567437afdaa <unknown>\n#7 0x5567437afa85 <unknown>\n#8 0x5567437ad8ee <unknown>\n#9 0x5567437ae0ca <unknown>\n#10 0x5567437caf99 <unknown>\n#11 0x556743865d65 <unknown>\n#12 0x55674383f3e2 <unknown>\n#13 0x55674386514f <unknown>\n#14 0x55674383f1b3 <unknown>\n#15 0x55674380b59b <unknown>\n#16 0x55674380c971 <unknown>\n#17 0x556743ced25b <unknown>\n#18 0x556743cf0fa9 <unknown>\n#19 0x556743cd4339 <unknown>\n#20 0x556743cf1b58 <unknown>\n#21 0x556743cb8c1f <unknown>\n#22 0x556743d15118 <unknown>\n#23 0x556743d152f6 <unknown>\n#24 0x556743d27066 <unknown>\n#25 0x7f68a589caa4 <unknown>\n#26 0x7f68a5929c3c <unknown>","time":{"start":1756971935234,"stop":1756971935644,"duration":410}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"568a08e052c1761f.json","parameterValues":[]}