{"uid":"77792fc36dd407db","name":"test_change_name","fullName":"tests.test_example.ExampleTestCase#test_change_name","historyId":"401c7467121e7dc775efa0719d6717a6","time":{"start":1756971940906,"stop":1756971948346,"duration":7440},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=139.0.7258.154)\nStacktrace:\n#0 0x563cc30ca08a <unknown>\n#1 0x563cc2b69a70 <unknown>\n#2 0x563cc2b60cf1 <unknown>\n#3 0x563cc2b52099 <unknown>\n#4 0x563cc2b53de0 <unknown>\n#5 0x563cc2b5243e <unknown>\n#6 0x563cc2b51daa <unknown>\n#7 0x563cc2b51a85 <unknown>\n#8 0x563cc2b4f8ee <unknown>\n#9 0x563cc2b500ca <unknown>\n#10 0x563cc2b6cf99 <unknown>\n#11 0x563cc2c07d65 <unknown>\n#12 0x563cc2be13e2 <unknown>\n#13 0x563cc2c0714f <unknown>\n#14 0x563cc2be11b3 <unknown>\n#15 0x563cc2bad59b <unknown>\n#16 0x563cc2bae971 <unknown>\n#17 0x563cc308f25b <unknown>\n#18 0x563cc3092fa9 <unknown>\n#19 0x563cc3076339 <unknown>\n#20 0x563cc3093b58 <unknown>\n#21 0x563cc305ac1f <unknown>\n#22 0x563cc30b7118 <unknown>\n#23 0x563cc30b72f6 <unknown>\n#24 0x563cc30c9066 <unknown>\n#25 0x7f13bfa9caa4 <unknown>\n#26 0x7f13bfb29c3c <unknown>","statusTrace":"self = <test_example.ExampleTestCase testMethod=test_change_name>\n\n    def test_change_name(self):\n>       self.home.open(OLLAMA_URL)\n\ntests/test_example.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/home_page.py:21: in open\n    self.driver.get(url)\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:483: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:458: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fbd32d8ea10>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#24 0x563cc30c9066 \\\\u003Cunknown>\\\\n#25 0x7f13bfa9caa4 \\\\u003Cunknown>\\\\n#26 0x7f13bfb29c3c \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                try:\n                    value = json.loads(value_json)\n                    if isinstance(value, dict):\n                        if len(value) == 1:\n                            value = value[\"value\"]\n                        status = value.get(\"error\", None)\n                        if not status:\n                            status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                            message = value.get(\"value\") or value.get(\"message\")\n                            if not isinstance(message, str):\n                                value = message\n                                message = message.get(\"message\")\n                        else:\n                            message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=139.0.7258.154)\nE       Stacktrace:\nE       #0 0x563cc30ca08a <unknown>\nE       #1 0x563cc2b69a70 <unknown>\nE       #2 0x563cc2b60cf1 <unknown>\nE       #3 0x563cc2b52099 <unknown>\nE       #4 0x563cc2b53de0 <unknown>\nE       #5 0x563cc2b5243e <unknown>\nE       #6 0x563cc2b51daa <unknown>\nE       #7 0x563cc2b51a85 <unknown>\nE       #8 0x563cc2b4f8ee <unknown>\nE       #9 0x563cc2b500ca <unknown>\nE       #10 0x563cc2b6cf99 <unknown>\nE       #11 0x563cc2c07d65 <unknown>\nE       #12 0x563cc2be13e2 <unknown>\nE       #13 0x563cc2c0714f <unknown>\nE       #14 0x563cc2be11b3 <unknown>\nE       #15 0x563cc2bad59b <unknown>\nE       #16 0x563cc2bae971 <unknown>\nE       #17 0x563cc308f25b <unknown>\nE       #18 0x563cc3092fa9 <unknown>\nE       #19 0x563cc3076339 <unknown>\nE       #20 0x563cc3093b58 <unknown>\nE       #21 0x563cc305ac1f <unknown>\nE       #22 0x563cc30b7118 <unknown>\nE       #23 0x563cc30b72f6 <unknown>\nE       #24 0x563cc30c9066 <unknown>\nE       #25 0x7f13bfa9caa4 <unknown>\nE       #26 0x7f13bfb29c3c <unknown>\n\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:232: WebDriverException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":5,"retriesStatusChange":false,"beforeStages":[{"name":"_unittest_setUpClass_fixture_ExampleTestCase","time":{"start":1756971940905,"stop":1756971940905,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"_unittest_setUpClass_fixture_ExampleTestCase::0","time":{"start":1756971949245,"stop":1756971949245,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_example"},{"name":"subSuite","value":"ExampleTestCase"},{"name":"host","value":"pkrvm7jw40e0xgp"},{"name":"thread","value":"2501-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_example"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"918f0ae3f52d861e","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//localhost%3A3000/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20localhost%3A3000.\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:910:5\ncheckReadyState@chrome://remote/content/marionette/navigate.sys.mjs:59:24\nonNavigation@chrome://remote/content/marionette/navigate.sys.mjs:348:39\nemit@resource://gre/modules/EventEmitter.sys.mjs:156:19\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.sys.mjs:33:25","time":{"start":1756971938405,"stop":1756971941297,"duration":2892}},{"uid":"7d9661439449cfc1","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//localhost%3A3000/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20localhost%3A3000.\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:910:5\ncheckReadyState@chrome://remote/content/marionette/navigate.sys.mjs:59:24\nonNavigation@chrome://remote/content/marionette/navigate.sys.mjs:348:39\nemit@resource://gre/modules/EventEmitter.sys.mjs:156:19\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.sys.mjs:33:25","time":{"start":1756971937900,"stop":1756971941553,"duration":3653}},{"uid":"39200cefe8a1044a","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//localhost%3A3000/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20localhost%3A3000.\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:910:5\ncheckReadyState@chrome://remote/content/marionette/navigate.sys.mjs:59:24\nonNavigation@chrome://remote/content/marionette/navigate.sys.mjs:348:39\nemit@resource://gre/modules/EventEmitter.sys.mjs:156:19\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.sys.mjs:33:25","time":{"start":1756971931759,"stop":1756971934654,"duration":2895}},{"uid":"78623e5f82f01fe9","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=139.0.7258.154)\nStacktrace:\n#0 0x565549eba08a <unknown>\n#1 0x565549959a70 <unknown>\n#2 0x565549950cf1 <unknown>\n#3 0x565549942099 <unknown>\n#4 0x565549943de0 <unknown>\n#5 0x56554994243e <unknown>\n#6 0x565549941daa <unknown>\n#7 0x565549941a85 <unknown>\n#8 0x56554993f8ee <unknown>\n#9 0x5655499400ca <unknown>\n#10 0x56554995cf99 <unknown>\n#11 0x5655499f7d65 <unknown>\n#12 0x5655499d13e2 <unknown>\n#13 0x5655499f714f <unknown>\n#14 0x5655499d11b3 <unknown>\n#15 0x56554999d59b <unknown>\n#16 0x56554999e971 <unknown>\n#17 0x565549e7f25b <unknown>\n#18 0x565549e82fa9 <unknown>\n#19 0x565549e66339 <unknown>\n#20 0x565549e83b58 <unknown>\n#21 0x565549e4ac1f <unknown>\n#22 0x565549ea7118 <unknown>\n#23 0x565549ea72f6 <unknown>\n#24 0x565549eb9066 <unknown>\n#25 0x7f80e669caa4 <unknown>\n#26 0x7f80e6729c3c <unknown>","time":{"start":1756971927065,"stop":1756971936327,"duration":9262}},{"uid":"c0bb21467b373dae","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=139.0.7258.154)\nStacktrace:\n#0 0x55c8fd5af08a <unknown>\n#1 0x55c8fd04ea70 <unknown>\n#2 0x55c8fd045cf1 <unknown>\n#3 0x55c8fd037099 <unknown>\n#4 0x55c8fd038de0 <unknown>\n#5 0x55c8fd03743e <unknown>\n#6 0x55c8fd036daa <unknown>\n#7 0x55c8fd036a85 <unknown>\n#8 0x55c8fd0348ee <unknown>\n#9 0x55c8fd0350ca <unknown>\n#10 0x55c8fd051f99 <unknown>\n#11 0x55c8fd0ecd65 <unknown>\n#12 0x55c8fd0c63e2 <unknown>\n#13 0x55c8fd0ec14f <unknown>\n#14 0x55c8fd0c61b3 <unknown>\n#15 0x55c8fd09259b <unknown>\n#16 0x55c8fd093971 <unknown>\n#17 0x55c8fd57425b <unknown>\n#18 0x55c8fd577fa9 <unknown>\n#19 0x55c8fd55b339 <unknown>\n#20 0x55c8fd578b58 <unknown>\n#21 0x55c8fd53fc1f <unknown>\n#22 0x55c8fd59c118 <unknown>\n#23 0x55c8fd59c2f6 <unknown>\n#24 0x55c8fd5ae066 <unknown>\n#25 0x7f536cc9caa4 <unknown>\n#26 0x7f536cd29c3c <unknown>","time":{"start":1756971926394,"stop":1756971934720,"duration":8326}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"77792fc36dd407db.json","parameterValues":[]}